import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Bundle the reading engine into one CommonJS file.
 *
 * The desktop app loads it as a child process, so everything must be reachable
 * with plain require(): two outputs, because the library and the launcher have
 * different jobs. The library never auto-starts, which is what lets it be
 * required from a test without binding a port.
 *
 * Third-party packages stay external. They live in this project's
 * node_modules like everything else, so a single install covers the app, the
 * engine and the tests.
 */
const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, 'dist');

const { build } = await import('esbuild');

await fs.promises.rm(OUT, { recursive: true, force: true });
await fs.promises.mkdir(OUT, { recursive: true });

await build({
  entryPoints: [path.join(HERE, 'server', 'src', 'index.ts')],
  outfile: path.join(OUT, 'server.cjs'),
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node22',
  packages: 'external',
  sourcemap: false,
  minify: false,
  logLevel: 'info',
  banner: {
    // `__dirname` is module-scoped in CommonJS, so publish it for the shared
    // path helper, which has to work in both module systems. Also silence
    // node:sqlite's experimental warning, which would otherwise be the first
    // thing a user sees.
    js: [
      "process.removeAllListeners('warning');",
      "if (typeof __dirname === 'string') { globalThis.__engineDir = __dirname; }",
    ].join('\n'),
  },
});

// The MTProto client writes its version banner straight to process.stdout, below
// any console wrapper, so it has to be filtered at the stream to keep a
// background process quiet. THETODO_DEBUG=1 turns everything back on.
const launcher = `// Generated by engine/build.mjs - do not edit.
if (!process.env.THETODO_DEBUG) {
  const write = process.stdout.write.bind(process.stdout);
  process.stdout.write = (chunk, ...rest) => {
    if (typeof chunk === "string" && /\\[INFO\\]|teleproto|LAYER \\d+/.test(chunk)) return true;
    return write(chunk, ...rest);
  };
}
const { startServer } = require("./server.cjs");
// No port argument: the server reads CLASSRADAR_PORT, which is the one name the
// launcher, the desktop shell and the docs all use. Passing 0 here would make
// every run pick a different port.
startServer(undefined, true).then((running) => {
  console.log("\\n  TheToDo reading engine  ->  " + running.url + "\\n");
  for (const sig of ["SIGINT", "SIGTERM"]) {
    process.on(sig, () => running.close().finally(() => process.exit(0)));
  }
});
`;

await fs.promises.writeFile(path.join(OUT, 'server-launcher.cjs'), launcher, 'utf8');
console.log(`[engine] built ${path.relative(process.cwd(), OUT)}`);
